[project]
name = "xero"
authors = [
    { name = "EPI-USE Global Services", email = "support@epiuse.com"}
]
description = "Integrate ERPNext with Xero Accounting"
requires-python = ">=3.14,<3.15"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=16.0.0" # Installed and managed by bench.
]

[tool.frappe]
frappe_version = ">=16.0.0,<17.0.0"
required_frappe_version = ">=16.0.0,<17.0.0"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"
